### ISSUE TITLE
Retrieve number of citations given PMIDs

### ISSUE THREAD

**Issue by trangdata** [dhimmel/pubmedpy#2]
It would be very useful to have a function that takes PMIDs and returns their corresponding number of citations. Perhaps interacting with the PubMed API following this guideline?
https://www.ncbi.nlm.nih.gov/pmc/tools/cites-citedby/

**Comment by dhimmel** [comment]
Ooh it looks like the `eSummaryResult/DocSum` elements we query for pubmed IDs have a `PmcRefCount` field, which I am guessing is the number of PMC articles which cite them. 

https://github.com/dhimmel/pubmedpy/blob/91024067f530f68886d3fbc14b6647afbc19941e/pubmedpy/tests/data/esummary.xml#L45

**Comment by dhimmel** [comment]
I added code to extract `pmc_cited_by_count` from `PmcRefCount` in https://github.com/dhimmel/pubmedpy/pull/3 for pubmed DocSum XML records. This XML structure is returned by the esummary API.

Note that `pmc_cited_by_count` is the number of articles in PMC that cite the PubMed article. Since PMC is a subset of all articles, this citation count is incomplete. But it is probably sufficient to gauge overall citation patterns and popularity of an article. 

The efetch API returns articles as `PubmedArticle` elements. Unfortunately, I didn't see any incoming citation information in that schema (although it does have outgoing citations under `ReferenceList`).

Therefore, if we want to get citation counts for the ISCB analysis ([notebook](https://github.com/greenelab/iscb-diversity/blob/7f4c566f067dee9e5c09d4e33377b631ee189d31/02.process-pubmed.ipynb)), we need to download esummary records for each article in addition to the efetch record (what we do now).

**Comment by trangdata** [comment]
> Note that pmc_cited_by_count is the number of articles in PMC that cite the PubMed article. Since PMC is a subset of all articles, this citation count is incomplete. But it is probably sufficient to gauge overall citation patterns and popularity of an article.

Thanks for emphasizing! I'll make sure to note this in the study.

> Therefore, if we want to get citation counts for the ISCB analysis (notebook), we need to download esummary records for each article in addition to the efetch record (what we do now).

If we could do this together one evening this week, that would be great! 🙏

**Comment by dhimmel** [comment]
Okay, done in https://github.com/greenelab/iscb-diversity/commit/74ea9a458bed1de204a5393a6b8e039a86aeaa19 and https://github.com/greenelab/iscb-diversity/commit/77c3b93fd1995db91db7a8ffbfbe5ed615f87154
